apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-content-template-renderer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-content-template-renderer
    app.kubernetes.io/part-of: insights-content-template-renderer
  name: insights-content-template-renderer
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: insights-content-template-renderer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: insights-content-template-renderer
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ccx-tenant/insights-content-template-renderer/insights-content-template-renderer@sha256:42402dac43c50dc39bf8971fc93da37efab968a8424069507cf28e90cd2fedda
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
